name: Run Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make setup_venv

      - name: Run Tests and Code Quality Checks
        run: |
          make checks

      - name: Setup DVC.
        run: |
          . .venv/bin/activate
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local \
              gdrive_service_account_json_file_path dvc-project-383101-f35837803686.json

      - name: Data Validation
        run: |
          echo "Pulling data from remote storage ..."
          . .venv/bin/activate && dvc pull data/salary.csv
          wc -l data/salary.csv
          echo "Changing directory to GX directory ..."
          cd tests/great_expectations/great_expectations
          echo "Running GX ..."
          great_expectations checkpoint run salary_data
